

services:
  app:
    container_name: node-container
    image: node-image
    build: 
      context: .
      args:
        - NODE_ENV=development
    # ports:
    #   - "3000:3000" # Exposes Node.js application on port 3000
    volumes:
      - .:/app # Bind mount for real-time development
      - /app/node_modules # Prevent overwriting node_modules
    environment:
      - NODE_ENV=development
    # depends_on:
    #   - mongo
    # env_file:
    #   - ./.env # Load environment variables from .env file
    # depends_on:
    #   - mongo
    command: npm run dev # Start with nodemon for auto-reloading
  nginx:
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
 

volumes:
  mongodb: {} # Ensure this is correctly formatted
